# Autor: Pablo Fernando Flores Magaña
# Número de Control : 17240273
# Repositorio: https://github.com/PFERHD7/Orquesta 
# Laboratorio para el Despliegue de Aplicaciones Empresariales
# Grupo 10:30 am
# Configuración del Volumen Persistente

apiVersion: v1                           # Versión de la Api
kind: PersistentVolume                   # Tipo de Objeto: Volumen Persistente
metadata:
  name: master-pv                        # Nombre del Objeto
  labels:
    type: persistente                    # Etiqueta de tipo (Nada en especial)
spec:
  storageClassName: masterfiles          # Nombre de la clase
  capacity:
    storage: 10Gi                        # Capacidad en Gigas
  accessModes:
    - ReadWriteOnce                      # Modo de Acceso Lectura-Escritura, solo por un nodo al mismo tiempo
  hostPath:
    path: "/master"                      # Carpeta de Almacenamiento 